### ISSUE TITLE
Request for collaboration

### ISSUE THREAD

**Issue by V-Roger** [edgarkech/scalable_field_camera#10]
Hello Edgar,

I worked on some exploded and assembly views in 3DFusion and would like to commit them but I'm no collaborator of the repo and thus am not allowed to.

![SFC_4x5_assembly (4)](https://user-images.githubusercontent.com/6457990/88689598-f344df80-d0fa-11ea-9a0e-dad6bea9d6a6.png)

Would love to help you out on this project, could you add me as a collaborator ?

Thanks a bunch,

Virgil

**Comment by edgarkech** [comment]
Nice work :-) - just invited you as collaborator

**Comment by V-Roger** [comment]
Thank you, I joined the repo!
