### ISSUE TITLE
4x5 front_lid_dovetail STL seems short

### ISSUE THREAD

**Issue by drdpj** [edgarkech/scalable_field_camera#12]
**Describe the bug**
The STL is short (4 screw holes in length instead of 5), and the scad won't render as it is

**Expected behavior**
I think it should be rendering with 5 holes, equal to the length of the front lid

**Pictures**
If applicable, add pictures to help explain your problem.

**Additional context**
Updated 4x5 config attached, which I think fixes things (params taken from 5x7 config)? Another eye over it would be useful before I commit to a print!
[config_4x5.zip](https://github.com/edgarkech/scalable_field_camera/files/7110569/config_4x5.zip)

**Comment by edgarkech** [comment]
sorry for the _very_ delayed response.
For the 4x5 version it does not matter if the dovetail is shorter than the lid - it won't add to stability/rigidity and it won't degrade functionality. So from my point of view this is not a real bug, especially if it is just a matter of configuration (as you found out).
