### ISSUE TITLE
body.stl files doesn't fit with body.scad

### ISSUE THREAD

**Issue by un-named-man** [edgarkech/scalable_field_camera#16]
the body has the same border, but the window is slightly smaller in body.stl, thus bellows_back_frame (which doesn't have stl version in STL_4x5) exported from .sacd cannot fit in the body part printed with body.stl (4x5 version). 

![屏幕截图 2024-07-01 091853](https://github.com/edgarkech/scalable_field_camera/assets/52991741/84319949-389b-494a-9497-f1aea90f5a04)

**Comment by edgarkech** [comment]
Hi,
the above screenshot looks quite mixed up. The body should be almost square and without any "double" structures as shown above. I checked the available STL which looks exactly as expected (see https://github.com/edgarkech/scalable_field_camera/blob/master/STL_4x5/body.stl).
What I noticed within the SCAD files:
For creating a proper 4x5 STLs from the SCAD files, you have to check the baseconfig.scad file. This file has multilple "include" statements for the format specific config files. Please make sure to comment in the "include <config_4x5.scad>;" line and comment out the "include <config_5x7.scad>;". Then save and re-render the SCAD-files before exporting to STL.

**Comment by edgarkech** [comment]
since there was no reaction to my suggestion, I am closing this issue.
